CREATE TABLE IF NOT EXISTS shorts (
    id CHAR(36) NOT NULL PRIMARY KEY,
    url TEXT NOT NULL,
    short_code VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    access_count INT NOT NULL DEFAULT 0
);
